### ISSUE TITLE
Create a group to manage readings

### ISSUE THREAD

**Issue by jrnold** [UW-POLS501/pols_501_wi16#17]
I want to create an online "group" for organizing references to any of the readings. The purposes are twofold: (1) introduce students to reference managers useful to their research through example, (2) perhaps have collaborative note-taking on the readings.

Should I use colwiz, mendeley or zotero? 
- mendeley: is polished, has good integration and exports, but Elsevier is evil
- colwiz: nice interaction with readings, but not good export
- zotero: not as polished

**Comment by jrnold** [comment]
@CasAndreu  Have you used any of these?

**Comment by CasAndreu** [comment]
I have used mendeley and zotero to manage my own references and take notes, but I never used them for collaborative note-taking. However, as you mention, mendeley is 'more polished' than zotero.

**Comment by jrnold** [comment]
I'll make a group in each and see which sucks the least.
