### ISSUE TITLE
Review data sources and install pages

### ISSUE THREAD

**Issue by jrnold** [UW-POLS501/pols_501_wi16#18]
Can you look over the [data sources](https://uw-pols501.github.io/pols_501_wi16/resources/data.html) and [installation](https://uw-pols501.github.io/pols_501_wi16/resources/install.html) pages? Check if there are any errors, and add anything you see fit / fix any errors.

**Comment by CasAndreu** [comment]
Ok, I'll take a look at it!

**Comment by CasAndreu** [comment]
Done! I fixed some bugs in the data sources site and added a new dataset (Party Manifesto project). I'll keep adding datasets.

**Comment by jrnold** [comment]
Once your done with it, you can close it.
