### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by jrnold** [UW-POLS501/pols_501_wi16#21]

**Comment by jrnold** [comment]
Needs to begin with plotting, since everybody loves pictures. 
- [ ] Identify the various panes in the Rstudio
- [ ] Be able to adjust preferences
- [ ] Turn off saving Rdata

This tutorial looks good http://blog.echen.me/2012/01/17/quick-introduction-to-ggplot2/

**Comment by jrnold** [comment]
In Lecture 1
- [ ] Intro to the Rstudio GUI
- [ ] Rstudio packages
- [ ] Basic interaction with dataframes: nrow, ncol, colnames, [, head, tail.
- [ ] Plotting gapminder data with R

Lab 1
- [x] Reading data in R's native format 
- [x] Read/write csv 
- [x] Read/write stata/spss/xls
- [x] Getting data from a source: WDI ? 
- [x] Dataverse and replication data
  - Show example of dataverse
  - Go to AJPS and look for data from a journal article
  - Go to APSR, JOP - 

Reading data in R: See notes in web/stories/resources/loading_data_in_r.md , 

What to cover?

New packages: `rio`, `haven`, `readxl`. 
1. Conceptual difference between text and binary data formats. 
2. Data in R: 
   - `data`
   - `gapminder` package or data-only packages
3. Saving data in R native format (RData, rda)
   - `save` 
   - `load`: Note that `load` is silent. It just appears in the environment without any message, unless there is an error. 
4. Common tabular data formats
   - csv
   - xls
   - Stata (dta)
   - SPSS
5. Example of data export on Dataverse in multiple formats
6. Data on the web: JSON, XML - Not tabular.
7. How to save and share data: use open/shareable formats?

**Comment by CasAndreu** [comment]
Do we want students to create an R script or an R Markdown document for the first lab? Maybe an R script would be a better/easier option? They can follow the Lab-RMarkdown file and the our live coding and copy/write lines of code in an R script they can run save at the end of the lab?

**Comment by jrnold** [comment]
R markdown documents. You can always create R scripts from that using `tangle()`.

**Comment by jrnold** [comment]
Keep working in that directory. Have 1 markdown file per logical unit of thought. I'm going to follow up in a bit.
